name: Node.js Benchmark Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24, 25]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Node.js version
        run: node --version

      - name: Run benchmark
        run: node bench.js
